#' Generate the utils.R Script
#'
#' Creates the project utility script with plotting, statistics, and
#' export helpers.
#'
#' @param project_dir Character. Path to the project root.
#' @param scheme A scheme list from [reflow_scheme()].
#'
#' @return Invisibly returns the output file path.
#'
#' @keywords internal
generate_utils_script <- function(project_dir, scheme) {
  s <- scheme

  utils_code <- glue::glue('
# ============================================================
# utils.R -- Utility Functions
# Scheme: {s$label}
# Auto-generated by reflowR -- customise as needed
# ============================================================

# ── Plot Helpers ──

#\' Save a ggplot to multiple formats
save_wf_plot <- function(plot, filename, dir = paths$figures,
                         width = 8, height = 5, dpi = 300,
                         formats = c("png", "pdf")) {{
  for (fmt in formats) {{
    out <- file.path(dir, paste0(filename, ".", fmt))
    ggplot2::ggsave(out, plot = plot, width = width, height = height,
                    dpi = dpi, bg = "white")
  }}
  cli::cli_alert_success("Plot saved: {{.val {{filename}}}}")
  invisible(file.path(dir, paste0(filename, ".", formats[1])))
}}

#\' Correlation heatmap
wf_cor_heatmap <- function(df, vars = NULL, method = "pearson", ...) {{
  if (is.null(vars)) vars <- names(df)[sapply(df, is.numeric)]
  cor_mat <- cor(df[, vars, drop = FALSE], use = "pairwise.complete.obs",
                 method = method)
  cor_long <- as.data.frame(as.table(cor_mat))
  names(cor_long) <- c("Var1", "Var2", "value")

  ggplot2::ggplot(cor_long, ggplot2::aes(Var1, Var2, fill = value)) +
    ggplot2::geom_tile(color = "white") +
    scale_fill_wf_diverging(limits = c(-1, 1), name = method) +
    ggplot2::geom_text(ggplot2::aes(label = sprintf("%.2f", value)),
                       size = 3, color = "black") +
    ggplot2::labs(x = NULL, y = NULL) +
    theme_wf() +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))
}}

#\' Box + jitter plot
wf_boxjitter <- function(df, x, y, fill = x, ...) {{
  ggplot2::ggplot(df, ggplot2::aes(.data[[x]], .data[[y]], fill = .data[[fill]])) +
    ggplot2::geom_boxplot(alpha = 0.7, outlier.shape = NA) +
    ggplot2::geom_jitter(width = 0.2, alpha = 0.4, size = 1.5) +
    scale_fill_wf() +
    theme_wf() +
    ggplot2::labs(...)
}}

#\' Histograms for all numeric vars
wf_histograms <- function(df, vars = NULL, bins = 30, ncol = 3) {{
  if (is.null(vars)) vars <- names(df)[sapply(df, is.numeric)]
  plots <- lapply(vars, function(v) {{
    ggplot2::ggplot(df, ggplot2::aes(.data[[v]])) +
      ggplot2::geom_histogram(bins = bins, fill = wf_colors$primary,
                              color = "white", alpha = 0.8) +
      theme_wf() +
      ggplot2::labs(title = v, x = NULL, y = "Count")
  }})
  patchwork::wrap_plots(plots, ncol = ncol)
}}

# ── Statistics Helpers ──

#\' Format p-value
fmt_pval <- function(p, digits = 3) {{
  dplyr::case_when(
    p < 0.001 ~ "< 0.001",
    p < 0.01  ~ sprintf("%.3f", p),
    TRUE      ~ sprintf(paste0("%.", digits, "f"), p)
  )
}}

#\' Frequency table
freq_table <- function(df, var, sort = TRUE) {{
  tbl <- df |>
    dplyr::count(.data[[var]], name = "n") |>
    dplyr::mutate(pct = round(n / sum(n) * 100, 1))
  if (sort) tbl <- dplyr::arrange(tbl, dplyr::desc(n))
  tbl
}}

#\' Coefficient of variation
cv <- function(x, na.rm = TRUE) {{
  sd(x, na.rm = na.rm) / mean(x, na.rm = na.rm) * 100
}}

#\' Missing data summary
missing_summary <- function(df) {{
  tibble::tibble(
    variable    = names(df),
    n_missing   = sapply(df, function(x) sum(is.na(x))),
    pct_missing = round(sapply(df, function(x) mean(is.na(x))) * 100, 1),
    n_complete  = nrow(df) - sapply(df, function(x) sum(is.na(x)))
  ) |>
    dplyr::arrange(dplyr::desc(pct_missing))
}}

#\' Numeric summary
numeric_summary <- function(df, vars = NULL) {{
  if (is.null(vars)) vars <- names(df)[sapply(df, is.numeric)]
  purrr::map_dfr(vars, function(v) {{
    x <- df[[v]]
    tibble::tibble(
      variable = v,
      n        = sum(!is.na(x)),
      mean     = mean(x, na.rm = TRUE),
      sd       = sd(x, na.rm = TRUE),
      median   = median(x, na.rm = TRUE),
      q25      = quantile(x, 0.25, na.rm = TRUE),
      q75      = quantile(x, 0.75, na.rm = TRUE),
      min      = min(x, na.rm = TRUE),
      max      = max(x, na.rm = TRUE)
    )
  }})
}}

# ── Table Helpers ──

#\' Styled kable
wf_kable <- function(df, caption = NULL, digits = 2, ...) {{
  knitr::kable(df, caption = caption, digits = digits, format = "html",
               ...) |>
    kableExtra::kable_styling(
      bootstrap_options = c("striped", "hover", "condensed"),
      full_width = FALSE, position = "center"
    )
}}

#\' Export to Excel
export_xlsx <- function(df, filename, dir = paths$tables, ...) {{
  out <- file.path(dir, paste0(filename, ".xlsx"))
  writexl::write_xlsx(df, out, ...)
  cli::cli_alert_success("Exported: {{.path {{out}}}}")
  invisible(out)
}}
')

  writeLines(utils_code, fs::path(project_dir, "code", "utils.R"))
  invisible(fs::path(project_dir, "code", "utils.R"))
}
