#' Generate the Code Library Files
#'
#' Creates `code/formulary.R`, `code/data_io.R`, `code/table_helpers.R`,
#' and `code/plot_helpers.R` in the project directory.
#'
#' @param project_dir Character. Path to the project root.
#' @param scheme A scheme list from [reflow_scheme()].
#' @param preset A preset list from [reflow_preset()].
#'
#' @return Invisibly returns a character vector of created file paths.
#'
#' @keywords internal
generate_code_library <- function(project_dir, scheme, preset) {
  code_dir <- fs::path(project_dir, "code")
  files <- character(4)

  # ── formulary.R ──
  files[1] <- fs::path(code_dir, "formulary.R")
  writeLines(generate_formulary_content(scheme), files[1])

  # ── data_io.R ──
  files[2] <- fs::path(code_dir, "data_io.R")
  writeLines(generate_data_io_content(scheme), files[2])

  # ── table_helpers.R ──
  files[3] <- fs::path(code_dir, "table_helpers.R")
  writeLines(generate_table_helpers_content(scheme), files[3])

  # ── plot_helpers.R ──
  files[4] <- fs::path(code_dir, "plot_helpers.R")
  writeLines(generate_plot_helpers_content(scheme), files[4])

  invisible(files)
}

# --- Internal content generators ---

generate_formulary_content <- function(scheme) {
  glue::glue('
# ============================================================
# formulary.R -- Reusable Analysis Recipes
# Sourced by Rmd files: source(here::here("code", "formulary.R"))
# Auto-generated by reflowR -- customise as needed
# ============================================================

source(here::here("code", "00_setup.R"))

# ── Normality Assessment ──
wf_normality_battery <- function(df, vars = NULL, alpha = 0.05) {{

  if (is.null(vars)) vars <- names(df)[sapply(df, is.numeric)]

  results <- purrr::map_dfr(vars, function(v) {{
    x <- df[[v]][!is.na(df[[v]])]
    if (length(x) < 3 || length(x) > 5000) {{
      return(tibble::tibble(variable = v, statistic = NA_real_,
                            p_value = NA_real_, normal = NA))
    }}
    test <- stats::shapiro.test(x)
    tibble::tibble(
      variable  = v,
      statistic = test$statistic,
      p_value   = test$p.value,
      normal    = test$p.value >= alpha
    )
  }})

  results
}}

# ── Group Comparison Selector ──
wf_compare_groups <- function(df, outcome, group, paired = FALSE) {{

  g <- df[[group]]
  y <- df[[outcome]]
  n_groups <- length(unique(g[!is.na(g)]))

  # Test normality per group
  norm_ok <- all(
    tapply(y, g, function(x) {{
      x <- x[!is.na(x)]
      if (length(x) < 3 || length(x) > 5000) return(TRUE)
      stats::shapiro.test(x)$p.value >= 0.05
    }})
  )

  if (n_groups == 2) {{
    if (norm_ok) {{
      test <- if (paired) stats::t.test(y ~ g, paired = TRUE) else stats::t.test(y ~ g)
      test_name <- ifelse(paired, "Paired t-test", "Welch t-test")
    }} else {{
      test <- if (paired) stats::wilcox.test(y ~ g, paired = TRUE) else stats::wilcox.test(y ~ g)
      test_name <- ifelse(paired, "Wilcoxon signed-rank", "Wilcoxon rank-sum")
    }}
    es <- effectsize::effectsize(test)
  }} else {{
    if (norm_ok) {{
      test <- stats::aov(as.formula(paste(outcome, "~", group)), data = df)
      test_name <- "One-way ANOVA"
      es <- effectsize::eta_squared(test)
    }} else {{
      test <- stats::kruskal.test(as.formula(paste(outcome, "~", group)), data = df)
      test_name <- "Kruskal-Wallis"
      es <- effectsize::rank_epsilon_squared(
        as.formula(paste(outcome, "~", group)), data = df
      )
    }}
  }}

  list(test_name = test_name, test = test, effect_size = es)
}}

# ── Automated Table 1 ──
wf_table_one <- function(df, strata = NULL, vars = NULL,
                         continuous_fn = "{{median}} ({{p25}}, {{p75}})",
                         categorical_fn = "{{n}} ({{p}}%)") {{

  tbl_args <- list(
    data = df,
    statistic = list(
      all_continuous()  ~ continuous_fn,
      all_categorical() ~ categorical_fn
    ),
    missing = "ifany"
  )
  if (!is.null(strata)) tbl_args$by <- strata
  if (!is.null(vars)) tbl_args$include <- dplyr::all_of(vars)

  tbl <- do.call(gtsummary::tbl_summary, tbl_args) |>
    gtsummary::bold_labels()

  if (!is.null(strata)) {{
    tbl <- tbl |> gtsummary::add_p() |> gtsummary::add_overall()
  }}

  tbl
}}

# ── Correlation Pipeline ──
wf_cor_analysis <- function(df, vars = NULL, method = "pearson",
                            threshold = 0.7, save_plot = TRUE) {{

  if (is.null(vars)) vars <- names(df)[sapply(df, is.numeric)]
  mat <- cor(df[, vars, drop = FALSE], use = "pairwise.complete.obs", method = method)

  # Find high correlations
  high_cors <- which(abs(mat) >= threshold & upper.tri(mat), arr.ind = TRUE)
  high_df <- if (nrow(high_cors) > 0) {{
    tibble::tibble(
      var1 = rownames(mat)[high_cors[, 1]],
      var2 = colnames(mat)[high_cors[, 2]],
      cor  = mat[high_cors]
    ) |> dplyr::arrange(dplyr::desc(abs(cor)))
  }} else {{
    tibble::tibble(var1 = character(), var2 = character(), cor = numeric())
  }}

  plot <- wf_cor_heatmap(df, vars = vars, method = method)
  if (save_plot) save_wf_plot(plot, "correlation_heatmap")

  list(matrix = mat, high_cors = high_df, plot = plot)
}}

# ── Missing Data Assessment ──
wf_missing_assessment <- function(df, pattern_plot = TRUE) {{

  summary_tbl <- missing_summary(df)
  pct_complete <- round(mean(stats::complete.cases(df)) * 100, 1)

  plots <- list()
  if (requireNamespace("naniar", quietly = TRUE)) {{
    plots$vis_miss <- naniar::vis_miss(df) + theme_wf()
    if (pattern_plot && ncol(df) <= 30 && sum(colSums(is.na(df)) > 0) >= 2) {{
      plots$upset <- tryCatch(naniar::gg_miss_upset(df), error = function(e) NULL)
    }}
  }}

  list(summary_table = summary_tbl, pct_complete = pct_complete, plots = plots)
}}

# ── Outlier Detection ──
wf_detect_outliers <- function(df, vars = NULL, method = c("iqr", "zscore"),
                               threshold = 1.5) {{
  method <- match.arg(method)
  if (is.null(vars)) vars <- names(df)[sapply(df, is.numeric)]

  purrr::map_dfr(vars, function(v) {{
    x <- df[[v]]
    if (method == "iqr") {{
      q <- quantile(x, c(0.25, 0.75), na.rm = TRUE)
      iqr <- q[2] - q[1]
      lower <- q[1] - threshold * iqr
      upper <- q[2] + threshold * iqr
    }} else {{
      mu <- mean(x, na.rm = TRUE)
      s  <- sd(x, na.rm = TRUE)
      lower <- mu - threshold * s
      upper <- mu + threshold * s
    }}
    tibble::tibble(
      variable    = v,
      row_id      = seq_along(x),
      value       = x,
      lower_bound = lower,
      upper_bound = upper,
      is_outlier  = !is.na(x) & (x < lower | x > upper)
    ) |> dplyr::filter(is_outlier)
  }})
}}

# ── Model Comparison Helper ──
wf_compare_models <- function(..., metrics = c("accuracy", "roc_auc")) {{
  results <- list(...)
  names(results) <- paste0("Model_", seq_along(results))
  if (!is.null(names(list(...)))) {{
    nn <- names(list(...))
    names(results)[nn != ""] <- nn[nn != ""]
  }}

  purrr::map_dfr(names(results), function(nm) {{
    res <- results[[nm]]
    if (inherits(res, "tune_results")) {{
      tune::collect_metrics(res) |>
        dplyr::filter(.metric %in% metrics) |>
        dplyr::mutate(model = nm)
    }} else {{
      tibble::tibble(model = nm, .metric = "custom", mean = NA_real_)
    }}
  }})
}}

# ── Checkpoint Loader ──
wf_load_checkpoint <- function(step_name, dir = paths$processed) {{
  pattern <- paste0("^", step_name, "_\\\\d{{8}}_\\\\d{{6}}\\\\.rds$")
  files <- list.files(dir, pattern = pattern, full.names = TRUE)
  if (length(files) == 0) {{
    cli::cli_abort("No checkpoint found for {{.val {{step_name}}}} in {{.path {{dir}}}}")
  }}
  latest <- files[which.max(file.info(files)$mtime)]
  cli::cli_alert_info("Loading checkpoint: {{.path {{basename(latest)}}}}")
  readRDS(latest)
}}
')
}


generate_data_io_content <- function(scheme) {
  glue::glue('
# ============================================================
# data_io.R -- Standardized Data Import / Export
# Sourced by Rmd files: source(here::here("code", "data_io.R"))
# Auto-generated by reflowR -- customise as needed
# ============================================================

source(here::here("code", "00_setup.R"))

# ── Universal Data Reader ──
wf_read_data <- function(file, sheet = 1, skip = 0,
                         na_strings = c("", "NA", "N/A", ".")) {{

  ext <- tolower(tools::file_ext(file))
  df <- switch(ext,
    csv  = readr::read_csv(file, skip = skip, na = na_strings, show_col_types = FALSE),
    tsv  = readr::read_tsv(file, skip = skip, na = na_strings, show_col_types = FALSE),
    xlsx = readxl::read_excel(file, sheet = sheet, skip = skip, na = na_strings),
    xls  = readxl::read_excel(file, sheet = sheet, skip = skip, na = na_strings),
    sav  = haven::read_sav(file),
    dta  = haven::read_dta(file),
    rds  = readRDS(file),
    rda  = {{ e <- new.env(); load(file, envir = e); as.list(e)[[1]] }},
    {{ cli::cli_abort("Unsupported file format: {{.val {{ext}}}}") }}
  )

  df <- janitor::clean_names(df)
  cli::cli_alert_success("Read {{.path {{basename(file)}}}}: {{nrow(df)}} rows x {{ncol(df)}} cols")
  tibble::as_tibble(df)
}}

# ── Batch Reader ──
wf_read_all <- function(dir = paths$raw, pattern = NULL, recursive = FALSE) {{
  exts <- c("csv", "tsv", "xlsx", "xls", "sav", "dta", "rds")
  if (is.null(pattern)) pattern <- paste0("\\\\.(", paste(exts, collapse = "|"), ")$")
  files <- list.files(dir, pattern = pattern, full.names = TRUE, recursive = recursive)
  if (length(files) == 0) {{
    cli::cli_warn("No data files found in {{.path {{dir}}}}")
    return(list())
  }}
  result <- purrr::map(files, wf_read_data)
  names(result) <- tools::file_path_sans_ext(basename(files))
  cli::cli_alert_success("Read {{length(result)}} file(s) from {{.path {{dir}}}}")
  result
}}

# ── Standardized Export ──
wf_export <- function(obj, filename, dir = NULL, formats = c("rds"),
                      versioned = FALSE) {{

  if (versioned) {{
    filename <- paste0(filename, "_", format(Sys.time(), "%Y%m%d_%H%M%S"))
  }}

  if (inherits(obj, "data.frame")) {{
    if (is.null(dir)) dir <- paths$processed
    for (fmt in formats) {{
      out <- file.path(dir, paste0(filename, ".", fmt))
      switch(fmt,
        rds  = saveRDS(obj, out),
        csv  = readr::write_csv(obj, out),
        xlsx = writexl::write_xlsx(obj, out),
        sav  = haven::write_sav(obj, out),
        cli::cli_warn("Unknown format: {{.val {{fmt}}}}")
      )
    }}
  }} else if (inherits(obj, "gg") || inherits(obj, "ggplot")) {{
    if (is.null(dir)) dir <- paths$figures
    save_wf_plot(obj, filename, dir = dir)
  }} else if (inherits(obj, c("gt_tbl", "gtsummary"))) {{
    if (is.null(dir)) dir <- paths$tables
    for (fmt in formats) {{
      out <- file.path(dir, paste0(filename, ".", fmt))
      switch(fmt,
        html = {{ gt_obj <- if (inherits(obj, "gtsummary")) gtsummary::as_gt(obj) else obj
                  gt::gtsave(gt_obj, out) }},
        docx = {{ ft <- if (inherits(obj, "gtsummary")) gtsummary::as_flex_table(obj)
                       else flextable::as_flextable(obj)
                  flextable::save_as_docx(ft, path = out) }},
        cli::cli_warn("Unknown format for table: {{.val {{fmt}}}}")
      )
    }}
  }} else {{
    if (is.null(dir)) dir <- paths$processed
    saveRDS(obj, file.path(dir, paste0(filename, ".rds")))
  }}

  cli::cli_alert_success("Exported: {{.val {{filename}}}}")
  invisible(filename)
}}

# ── Data Dictionary Generator ──
wf_data_dict <- function(df, output_file = NULL) {{

  dict <- purrr::map_dfr(names(df), function(v) {{
    x <- df[[v]]
    tibble::tibble(
      variable       = v,
      type           = class(x)[1],
      n_unique       = length(unique(x[!is.na(x)])),
      n_missing      = sum(is.na(x)),
      pct_missing    = round(mean(is.na(x)) * 100, 1),
      min            = if (is.numeric(x)) as.character(round(min(x, na.rm = TRUE), 4)) else NA_character_,
      max            = if (is.numeric(x)) as.character(round(max(x, na.rm = TRUE), 4)) else NA_character_,
      example_values = paste(utils::head(unique(x[!is.na(x)]), 3), collapse = ", ")
    )
  }})

  if (!is.null(output_file)) {{
    writexl::write_xlsx(dict, output_file)
    cli::cli_alert_success("Data dictionary saved: {{.path {{output_file}}}}")
  }}

  dict
}}

# ── Label Extractor (SPSS / REDCap) ──
wf_extract_labels <- function(df) {{
  purrr::map_dfr(names(df), function(v) {{
    x <- df[[v]]
    var_label <- attr(x, "label") %||% NA_character_
    val_labels <- attr(x, "labels")
    val_str <- if (!is.null(val_labels)) {{
      paste(paste0(val_labels, " = ", names(val_labels)), collapse = "; ")
    }} else NA_character_
    tibble::tibble(variable = v, label = var_label, value_labels = val_str)
  }})
}}
')
}


generate_table_helpers_content <- function(scheme) {
  glue::glue('
# ============================================================
# table_helpers.R -- Publication-Ready Table Builders
# Sourced by Rmd files: source(here::here("code", "table_helpers.R"))
# Auto-generated by reflowR -- customise as needed
# ============================================================

source(here::here("code", "00_setup.R"))

# ── Styled gtsummary Table ──
wf_tbl_summary <- function(df, by = NULL, include = dplyr::everything(),
                           type = NULL, statistic = NULL,
                           label = NULL, missing = "ifany") {{

  args <- list(data = df, include = include, missing = missing)
  if (!is.null(by)) args$by <- by
  if (!is.null(type)) args$type <- type
  if (!is.null(statistic)) args$statistic <- statistic
  if (!is.null(label)) args$label <- label

  tbl <- do.call(gtsummary::tbl_summary, args) |>
    gtsummary::bold_labels()

  if (!is.null(by)) {{
    tbl <- tbl |> gtsummary::add_p() |> gtsummary::add_overall()
  }}

  tbl
}}

# ── Regression Table ──
wf_tbl_regression <- function(model, exponentiate = FALSE,
                              show_ci = TRUE, show_p = TRUE) {{
  tbl <- gtsummary::tbl_regression(model, exponentiate = exponentiate) |>
    gtsummary::bold_labels() |>
    gtsummary::bold_p()
  tbl
}}

# ── Side-by-Side Model Table ──
wf_tbl_merge <- function(..., tab_spanner = NULL) {{
  tbls <- list(...)
  gtsummary::tbl_merge(tbls, tab_spanner = tab_spanner)
}}

# ── gt Export Pipeline ──
wf_gt_save <- function(gt_tbl, filename, dir = paths$tables,
                       formats = c("html", "docx")) {{
  gt_styled <- gt_wf_style(gt_tbl)
  for (fmt in formats) {{
    out <- file.path(dir, paste0(filename, ".", fmt))
    switch(fmt,
      html = gt::gtsave(gt_styled, out),
      docx = {{
        ft <- gt_styled |> flextable::as_flextable()
        flextable::save_as_docx(ft, path = out)
      }},
      png  = gt::gtsave(gt_styled, out),
      cli::cli_warn("Unknown format: {{.val {{fmt}}}}")
    )
  }}
  cli::cli_alert_success("Table saved: {{.val {{filename}}}}")
  invisible(file.path(dir, paste0(filename, ".", formats[1])))
}}

# ── Inline Results Formatter ──
wf_inline <- function(x, digits = 2, type = c("number", "p", "ci"),
                      prefix = "", suffix = "") {{
  type <- match.arg(type)
  result <- switch(type,
    number = sprintf(paste0("%.", digits, "f"), x[1]),
    p = {{
      if (x[1] < 0.001) "< 0.001"
      else if (x[1] < 0.01) sprintf("%.3f", x[1])
      else sprintf(paste0("%.", digits, "f"), x[1])
    }},
    ci = {{
      if (length(x) >= 2) {{
        sprintf(paste0("%.", digits, "f (95%% CI: %.", digits, "f, %.", digits, "f)"),
                x[1], x[1], x[2])
      }} else sprintf(paste0("%.", digits, "f"), x[1])
    }}
  )
  paste0(prefix, result, suffix)
}}

# ── Frequency Cross-Table ──
wf_crosstab <- function(df, row_var, col_var, margins = TRUE, test = TRUE) {{
  tbl <- df |>
    dplyr::count(.data[[row_var]], .data[[col_var]]) |>
    tidyr::pivot_wider(names_from = dplyr::all_of(col_var), values_from = n, values_fill = 0)

  gt_tbl <- gt::gt(tbl, rowname_col = row_var) |> gt_wf_style()

  if (test) {{
    ct <- stats::chisq.test(table(df[[row_var]], df[[col_var]]))
    gt_tbl <- gt_tbl |>
      gt::tab_footnote(sprintf("Chi-squared = %.2f, df = %d, p = %s",
                               ct$statistic, ct$parameter, fmt_pval(ct$p.value)))
  }}

  gt_tbl
}}
')
}


generate_plot_helpers_content <- function(scheme) {
  glue::glue('
# ============================================================
# plot_helpers.R -- Scheme-Aware Plot Constructors
# Sourced by Rmd files: source(here::here("code", "plot_helpers.R"))
# Auto-generated by reflowR -- customise as needed
# ============================================================

source(here::here("code", "00_setup.R"))

# ── Forest Plot ──
wf_forest_plot <- function(estimates, ci_lower, ci_upper, labels,
                           null_value = 1, log_scale = FALSE,
                           title = NULL) {{

  df <- tibble::tibble(
    label    = factor(labels, levels = rev(labels)),
    estimate = estimates,
    ci_lower = ci_lower,
    ci_upper = ci_upper
  )

  p <- ggplot2::ggplot(df, ggplot2::aes(x = estimate, y = label)) +
    ggplot2::geom_vline(xintercept = null_value, linetype = "dashed",
                        color = wf_colors$grey) +
    ggplot2::geom_errorbarh(ggplot2::aes(xmin = ci_lower, xmax = ci_upper),
                            height = 0.2, color = wf_colors$primary, linewidth = 0.8) +
    ggplot2::geom_point(size = 3, color = wf_colors$primary, fill = wf_colors$primary_light,
                        shape = 21) +
    theme_wf() +
    ggplot2::labs(x = "Estimate", y = NULL, title = title)

  if (log_scale) p <- p + ggplot2::scale_x_log10()
  p
}}

# ── Kaplan-Meier Plot ──
wf_km_plot <- function(survfit_obj, risk_table = TRUE, title = NULL,
                       palette = wf_palette) {{
  if (!requireNamespace("survminer", quietly = TRUE)) {{
    cli::cli_abort("Package {{.pkg survminer}} is required for KM plots.")
  }}
  survminer::ggsurvplot(
    survfit_obj,
    palette    = palette,
    risk.table = risk_table,
    ggtheme    = theme_wf(),
    title      = title,
    xlab       = "Time",
    ylab       = "Survival probability"
  )
}}

# ── ROC Curve ──
wf_roc_plot <- function(..., title = "ROC Curve") {{
  roc_data <- list(...)
  colors <- wf_palette[seq_along(roc_data)]

  p <- ggplot2::ggplot() +
    ggplot2::geom_abline(slope = 1, intercept = 0, linetype = "dashed",
                         color = wf_colors$grey)

  for (i in seq_along(roc_data)) {{
    rd <- roc_data[[i]]
    if (inherits(rd, "data.frame") && all(c("specificity", "sensitivity") %in% names(rd))) {{
      p <- p + ggplot2::geom_line(data = rd,
        ggplot2::aes(x = 1 - specificity, y = sensitivity),
        color = colors[i], linewidth = 1)
    }}
  }}

  p + theme_wf() +
    ggplot2::labs(x = "1 - Specificity", y = "Sensitivity", title = title) +
    ggplot2::coord_equal()
}}

# ── Calibration Plot ──
wf_calibration_plot <- function(predicted, observed, n_bins = 10, title = NULL) {{

  df <- tibble::tibble(predicted = predicted, observed = observed) |>
    dplyr::mutate(bin = cut(predicted, breaks = n_bins, include.lowest = TRUE)) |>
    dplyr::group_by(bin) |>
    dplyr::summarise(
      mean_pred = mean(predicted),
      mean_obs  = mean(observed),
      n = dplyr::n(),
      .groups = "drop"
    )

  ggplot2::ggplot(df, ggplot2::aes(x = mean_pred, y = mean_obs)) +
    ggplot2::geom_abline(slope = 1, intercept = 0, linetype = "dashed",
                         color = wf_colors$grey) +
    ggplot2::geom_point(size = 3, color = wf_colors$primary) +
    ggplot2::geom_line(color = wf_colors$primary_light, linewidth = 0.8) +
    theme_wf() +
    ggplot2::labs(x = "Predicted", y = "Observed", title = title) +
    ggplot2::coord_equal()
}}

# ── Faceted Distribution ──
wf_distributions <- function(df, vars = NULL, fill_var = NULL,
                             type = c("histogram", "density", "both"),
                             ncol = 3) {{
  type <- match.arg(type)
  if (is.null(vars)) vars <- names(df)[sapply(df, is.numeric)]

  plots <- lapply(vars, function(v) {{
    p <- ggplot2::ggplot(df, ggplot2::aes(.data[[v]]))
    if (type %in% c("histogram", "both")) {{
      p <- p + ggplot2::geom_histogram(fill = wf_colors$primary, color = "white",
                                       alpha = 0.7, bins = 30)
    }}
    if (type %in% c("density", "both")) {{
      p <- p + ggplot2::geom_density(color = wf_colors$accent, linewidth = 1,
                                     fill = wf_colors$primary_light, alpha = 0.3)
    }}
    p + theme_wf() + ggplot2::labs(title = v, x = NULL, y = NULL)
  }})

  patchwork::wrap_plots(plots, ncol = ncol)
}}

# ── Paired Before-After Plot ──
wf_paired_plot <- function(df, id, time_var, value_var, title = NULL) {{

  ggplot2::ggplot(df, ggplot2::aes(x = .data[[time_var]], y = .data[[value_var]],
                                   group = .data[[id]])) +
    ggplot2::geom_line(alpha = 0.3, color = wf_colors$grey) +
    ggplot2::geom_point(alpha = 0.4, color = wf_colors$primary, size = 2) +
    ggplot2::stat_summary(ggplot2::aes(group = 1), fun = mean, geom = "line",
                          color = wf_colors$accent, linewidth = 1.5) +
    ggplot2::stat_summary(ggplot2::aes(group = 1), fun = mean, geom = "point",
                          color = wf_colors$accent, size = 4) +
    theme_wf() +
    ggplot2::labs(title = title, x = time_var, y = value_var)
}}

# ── Volcano Plot ──
wf_volcano_plot <- function(results, fc_col = "log2fc", p_col = "p_value",
                            fc_threshold = 1, p_threshold = 0.05,
                            label_col = NULL, title = NULL) {{

  df <- results |>
    dplyr::mutate(
      neg_log_p = -log10(.data[[p_col]]),
      significance = dplyr::case_when(
        abs(.data[[fc_col]]) >= fc_threshold & .data[[p_col]] < p_threshold ~ "Significant",
        TRUE ~ "NS"
      )
    )

  p <- ggplot2::ggplot(df, ggplot2::aes(x = .data[[fc_col]], y = neg_log_p,
                                        color = significance)) +
    ggplot2::geom_point(alpha = 0.6, size = 1.5) +
    ggplot2::scale_color_manual(values = c("Significant" = wf_colors$accent,
                                           "NS" = wf_colors$grey)) +
    ggplot2::geom_hline(yintercept = -log10(p_threshold), linetype = "dashed",
                        color = wf_colors$grey) +
    ggplot2::geom_vline(xintercept = c(-fc_threshold, fc_threshold),
                        linetype = "dashed", color = wf_colors$grey) +
    theme_wf() +
    ggplot2::labs(x = "Log2 Fold Change", y = "-Log10 P-value", title = title)

  if (!is.null(label_col)) {{
    sig_df <- dplyr::filter(df, significance == "Significant")
    p <- p + ggrepel::geom_text_repel(
      data = sig_df,
      ggplot2::aes(label = .data[[label_col]]),
      size = 3, max.overlaps = 20
    )
  }}

  p
}}

# ── Multi-Panel Figure Builder ──
wf_compose <- function(..., ncol = 2, tag_levels = "A", title = NULL) {{
  p <- patchwork::wrap_plots(..., ncol = ncol) +
    patchwork::plot_annotation(
      tag_levels = tag_levels,
      title = title,
      theme = theme_wf()
    )
  p
}}
')
}
