#' Generate the 00_setup.R Script
#'
#' Creates the project setup script with package loading, paths, color
#' definitions, ggplot2 theme, and table styling helpers.
#'
#' @param project_dir Character. Path to the project root.
#' @param scheme A scheme list from [reflow_scheme()].
#'
#' @return Invisibly returns the output file path.
#'
#' @keywords internal
generate_setup_script <- function(project_dir, scheme) {
  s <- scheme
  pal_str <- paste0('c("', paste(s$palette, collapse = '", "'), '")')

  setup <- glue::glue('
# ============================================================
# 00_setup.R -- Project Setup & Configuration
# Scheme: {s$label}
# Auto-generated by reflowR -- customise as needed
# ============================================================

# ── Load packages ──
if (!requireNamespace("pacman", quietly = TRUE)) install.packages("pacman")
pacman::p_load(
  # Data wrangling

tidyverse, data.table, janitor, lubridate,
  # Paths
  here,
  # Tables
  gtsummary, gt, flextable, knitr, rmarkdown,
  # Plotting
  ggplot2, patchwork, ggrepel, scales, ggpubr, rstatix,
  # Statistics
  broom, effectsize,
  # Missing data
  naniar,
  # Modelling
  tidymodels, glmnet, ranger,
  # Dimensionality reduction
  FactoMineR, factoextra, umap, Rtsne,
  # I/O
  readxl, writexl, haven, rio,
  # Workflow
  workflowr
)

# ── Project paths ──
paths <- list(
  root      = here::here(),
  data      = here::here("data"),
  raw       = here::here("data", "raw"),
  processed = here::here("data", "processed"),
  code      = here::here("code"),
  output    = here::here("output"),
  figures   = here::here("output", "figures"),
  tables    = here::here("output", "tables"),
  models    = here::here("output", "models"),
  analysis  = here::here("analysis"),
  assets    = here::here("assets"),
  report    = here::here("report")
)

# ── Scheme colors ──
wf_colors <- list(
  primary       = "{s$primary}",
  primary_light = "{s$primary_light}",
  accent        = "{s$accent}",
  secondary     = "{s$secondary}",
  light_grey    = "{s$light_grey}",
  grey          = "{s$grey}",
  dark          = "{s$dark}",
  white         = "{s$white}"
)

wf_palette <- {pal_str}

# ── ggplot2 color scales ──
scale_color_wf <- function(...) {{
  ggplot2::scale_color_manual(values = wf_palette, ...)
}}

scale_fill_wf <- function(...) {{
  ggplot2::scale_fill_manual(values = wf_palette, ...)
}}

scale_color_wf_gradient <- function(...) {{
  ggplot2::scale_color_gradient(low = wf_colors$primary_light,
                                high = wf_colors$secondary, ...)
}}

scale_fill_wf_gradient <- function(...) {{
  ggplot2::scale_fill_gradient(low = wf_colors$primary_light,
                               high = wf_colors$secondary, ...)
}}

scale_color_wf_diverging <- function(...) {{
  ggplot2::scale_color_gradient2(low = wf_colors$accent,
                                 mid = wf_colors$light_grey,
                                 high = wf_colors$primary, ...)
}}

scale_fill_wf_diverging <- function(...) {{
  ggplot2::scale_fill_gradient2(low = wf_colors$accent,
                                mid = wf_colors$light_grey,
                                high = wf_colors$primary, ...)
}}

# ── ggplot2 theme ──
theme_wf <- function(base_size = 12) {{
  ggplot2::theme_minimal(base_size = base_size) +
    ggplot2::theme(
      text             = ggplot2::element_text(family = "sans", color = wf_colors$dark),
      plot.title       = ggplot2::element_text(face = "bold", size = base_size * 1.3,
                                               color = wf_colors$dark, margin = ggplot2::margin(b = 10)),
      plot.subtitle    = ggplot2::element_text(size = base_size * 1.05,
                                               color = wf_colors$grey, margin = ggplot2::margin(b = 10)),
      plot.caption     = ggplot2::element_text(size = base_size * 0.8,
                                               color = wf_colors$grey, hjust = 0),
      axis.title       = ggplot2::element_text(face = "bold", size = base_size * 0.95),
      axis.text        = ggplot2::element_text(size = base_size * 0.85, color = wf_colors$grey),
      legend.position  = "bottom",
      legend.title     = ggplot2::element_text(face = "bold", size = base_size * 0.9),
      legend.text      = ggplot2::element_text(size = base_size * 0.85),
      panel.grid.major = ggplot2::element_line(color = "#E8E8E8", linewidth = 0.3),
      panel.grid.minor = ggplot2::element_blank(),
      strip.text       = ggplot2::element_text(face = "bold", size = base_size * 0.95,
                                               color = wf_colors$white),
      strip.background = ggplot2::element_rect(fill = wf_colors$primary, color = NA),
      plot.background  = ggplot2::element_rect(fill = "white", color = NA),
      panel.background = ggplot2::element_rect(fill = "white", color = NA)
    )
}}

ggplot2::theme_set(theme_wf())

# ── gtsummary theme ──
wf_gtsummary_theme <- list(
  "tbl_summary-str:default_con" = "{{median}} ({{p25}}, {{p75}})",
  "tbl_summary-str:default_cat" = "{{n}} ({{p}}%)",
  "style_number-arg:big.mark"   = ","
)
gtsummary::set_gtsummary_theme(wf_gtsummary_theme)

# ── gt styling helper ──
gt_wf_style <- function(gt_tbl) {{
  gt_tbl |>
    gt::tab_options(
      table.font.names         = "Source Sans Pro, sans-serif",
      heading.title.font.size  = gt::px(18),
      heading.title.font.weight = "bold",
      column_labels.font.weight = "bold",
      column_labels.background.color = wf_colors$primary,
      column_labels.font.color = wf_colors$white,
      row_group.background.color     = wf_colors$primary_light,
      row_group.font.color           = wf_colors$white,
      table.border.top.color   = wf_colors$primary,
      table.border.top.width   = gt::px(3),
      table.border.bottom.color = wf_colors$grey,
      row.striping.background_color = paste0(wf_colors$light_grey, "80")
    ) |>
    gt::opt_row_striping() |>
    gt::opt_table_outline(color = wf_colors$primary)
}}

# ── knitr defaults ──
knitr::opts_chunk$set(
  fig.width  = 8,
  fig.height = 5,
  fig.retina = 2,
  dpi        = 150,
  warning    = FALSE,
  message    = FALSE,
  echo       = TRUE,
  fig.path   = here::here("output", "figures", "")
)

# ── Versioned checkpoint saver ──
save_versioned <- function(obj, name, dir = paths$processed) {{
  ts  <- format(Sys.time(), "%Y%m%d_%H%M%S")
  out <- file.path(dir, paste0(name, "_", ts, ".rds"))
  saveRDS(obj, out)
  cli::cli_alert_success("Saved checkpoint: {{.path {{out}}}}")
  invisible(out)
}}

# ── Session info footer ──
cat("\\n== Setup loaded ==\\n")
cat("Scheme:", "{s$label}", "\\n")
cat("Date:  ", format(Sys.Date(), "%d %B %Y"), "\\n")
')
  writeLines(setup, fs::path(project_dir, "code", "00_setup.R"))
  invisible(fs::path(project_dir, "code", "00_setup.R"))
}
